#!/usr/bin/env python3
import sys


def solve(K: int):
    if K <= 12:
        print(K)
        return
    # a = []
    # for i in range(1,10000):
    #     s = str(i)
    #     for j in range(len(s)-1):
    #         if abs(int(s[j])-int(s[j+1]))<=1:
    #             continue
    #         else:
    #             break
    #     else:
    #         a.append(i)
    # print(a)
    # matrix[i][j] = i桁で最上位がjから始まるものの数
    matrix = [[0]*10 for _ in range(11)]

    for i in range(0,10):
        matrix[1][i] = 1

    keta = 2
    SUM = 9
    last = 0
    while True:
        for i in range(10):
            if SUM >= K:
                break

            if i == 0:                
                matrix[keta][i] = matrix[keta-1][0]+matrix[keta-1][1]
            elif i == 9:
                matrix[keta][i] = matrix[keta-1][i-1]+matrix[keta-1][i]
            else:
                matrix[keta][i] = matrix[keta-1][i-1]+matrix[keta-1][i]+matrix[keta-1][i+1]

            if i > 0:
                SUM += matrix[keta][i]
            last = i

        else:
            keta += 1
            continue
        
        break

    answer = str(last)

    while keta > 0:
        i = int(answer[-1])
        SUM -= matrix[keta][i]
        keta -= 1
 
        if i == 0:                
            for j in range(0,2):
                SUM += matrix[keta][j]
                if SUM >= K:
                    answer += str(j)
                    break        
        elif i == 9:
            for j in range(8,10):
                SUM += matrix[keta][j]
                if SUM >= K:
                    answer += str(j)
                    break
        else:
            for j in range(i-1,i+2):
                SUM += matrix[keta][j]
                if SUM >= K:
                    answer += str(j)
                    break
    print(answer)

    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    K = int(next(tokens))  # type: int
    solve(K)

if __name__ == '__main__':
    main()
