#!/usr/bin/env python3
import sys


def solve(N: int, K: int, R: int, S: int, P: int, T: str):

    winToR = P
    winToS = R
    winToP = S
    # init
    dp = []
    for i in range(K):
        dp.append([])
        for _ in range(N // K + 1):
            m = [0] * 3
            dp[i].append(m)

    for k in range(K):
        if T[k] == "r":
            dp[k][0][0] = winToR
        elif T[k] == "s":
            dp[k][0][1] = winToS
        else:
            dp[k][0][2] = winToP

    for n in range(K, N):
        if T[n] == "r":

            dp[n % K][n // K][0] = winToR + max(dp[n % K][n // K - 1][1], dp[n % K][n // K - 1][2])
            dp[n % K][n // K][1] = max(dp[n % K][n // K - 1][0], dp[n % K][n // K - 1][2])
            dp[n % K][n // K][2] = max(dp[n % K][n // K - 1][0], dp[n % K][n // K - 1][1])
        elif T[n] == "s":
            dp[n % K][n // K][0] = max(dp[n % K][n // K - 1][1], dp[n % K][n // K - 1][2])
            dp[n % K][n // K][1] = winToS + max(dp[n % K][n // K - 1][0], dp[n % K][n // K - 1][2])
            dp[n % K][n // K][2] = max(dp[n % K][n // K - 1][0], dp[n % K][n // K - 1][1])
        else:
            dp[n % K][n // K][0] = max(dp[n % K][n // K - 1][1], dp[n % K][n // K - 1][2])
            dp[n % K][n // K][1] = max(dp[n % K][n // K - 1][0], dp[n % K][n // K - 1][2])
            dp[n % K][n // K][2] = winToP + max(dp[n % K][n // K - 1][0], dp[n % K][n // K - 1][1])

    sum = 0
    for k in range(N - K, N):
        imax = 0
        for i in range(3):
            imax = max(imax, dp[k % K][k // K][i])
        sum += imax

    print(sum)




    return


# Generated by 1.1.6 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    R = int(next(tokens))  # type: int
    S = int(next(tokens))  # type: int
    P = int(next(tokens))  # type: int
    T = next(tokens)  # type: str
    solve(N, K, R, S, P, T)

if __name__ == '__main__':
    main()
