#!/usr/bin/env python3
import sys
from collections import defaultdict, deque

inf = float('inf')


class Dinic(object):
    def __init__(self):
        self.V = set()
        self.adj = defaultdict(list)
        self.c = defaultdict(lambda: 0)
        self.f = defaultdict(lambda: 0)
        self.iter = defaultdict(lambda: 0)
    
    def add_edge(self, u, v, cap):
        self.V.add(u)
        self.V.add(v)
        self.adj[u].append(v)
        self.adj[v].append(u)
        self.c[(u, v)] = cap
    
    def bfs(self, s):
        self.level = {v: inf for v in self.V}
        self.level[s] = 0
        Q = deque([s])
        while len(Q) > 0:
            u = Q.popleft()
            for v in self.adj[u]:
                if self.c[(u, v)] <= 0:
                    continue
                if self.level[v] <= self.level[u]:
                    continue
                self.level[v] = self.level[u] + 1
                Q.append(v)
    
    def dfs(self, u, t, mincap):
        if u == t:
            return mincap

        for i in range(self.iter[u], len(self.adj[u])):
            self.iter[u] = i
            v = self.adj[u][i]
            if self.c[(u, v)] <= 0:
                continue
            if self.level[v] <= self.level[u]:
                continue
            d = self.dfs(v, t, min(mincap, self.c[(u, v)]))
            if d > 0:
                self.c[(u, v)] -= d
                self.c[(v, u)] += d
                return d
        return 0

    def max_flow(self, s, t):
        flow = 0
        
        while True:
            self.bfs(s)

            if self.level[t] == inf:
                return flow
        
            self.iter = defaultdict(lambda: 0)
            d = self.dfs(s, t, inf)
            while d > 0:
                flow += d
                d = self.dfs(s, t, inf)


def solve(N: int, a: "List[int]", b: "List[int]", c: "List[int]", d: "List[int]"):
    G = Dinic()
    for xr, yr in zip(a, b):
        G.add_edge(0, (xr, yr), 1)
        for xb, yb in zip(c, d):
            if xr < xb and yr < yb:
                G.add_edge((xr, yr), (xb, yb), 1)
    for xb, yb in zip(c, d):
        G.add_edge((xb, yb), 1, 1)
    print(G.max_flow(0, 1))
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    a = [int()] * (N)  # type: "List[int]" 
    b = [int()] * (N)  # type: "List[int]" 
    for i in range(N):
        a[i] = int(next(tokens))
        b[i] = int(next(tokens))
    c = [int()] * (N)  # type: "List[int]" 
    d = [int()] * (N)  # type: "List[int]" 
    for i in range(N):
        c[i] = int(next(tokens))
        d[i] = int(next(tokens))
    solve(N, a, b, c, d)

if __name__ == '__main__':
    main()
