#!/usr/bin/env python3
import sys


def solve(N: int, K: int, S: str):
    ranlength = []
    lastBit = ""
    lastLength = 0
    for c in S:
        if lastBit == "":
            lastBit = c
            lastLength += 1
            continue
        if lastBit == c:
            lastLength += 1
            continue
        else:
            ranlength.append((lastLength, int(lastBit)))
            lastLength = 1
            lastBit = c
            continue
    ranlength.append((lastLength, int(lastBit)))
    count0 = 0
    length0 = 0
    end = 0
    for i in range(len(ranlength)):
        if count0 == K and ranlength[i][1] == 0:
            break
        if ranlength[i][1] == 0:
            count0 += 1
        length0 += ranlength[i][0]
        end = i
    # これで最初のKこの入れ替えでの長さが求まる
    nextLength = length0
    lastMax = length0
    begin = 0
    #print(begin, end, nextLength)
    while end + 1 < len(ranlength):
        nextLength += ranlength[end + 1][0]
        end += 1
        for i in range(end + 1, len(ranlength)):
            if ranlength[i][1] == 0:
                break
            else:
                nextLength += ranlength[i][0]
            end = i
        for i in range(begin, len(ranlength)):
            begin = i + 1
            nextLength -= ranlength[i][0]
            if ranlength[i][1] == 0:
                break
        lastMax = max(lastMax, nextLength)
        #print(begin, end, nextLength)
    #print(lastMax, begin, end)
    print(lastMax)
    return


# Generated by 1.1.4 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
def main():
    def iterate_tokens():
        for line in sys.stdin:
            for word in line.split():
                yield word
    tokens = iterate_tokens()
    N = int(next(tokens))  # type: int
    K = int(next(tokens))  # type: int
    S = next(tokens)  # type: int
    # print(S)
    solve(N, K, S)


if __name__ == '__main__':
    main()
